### ISSUE TITLE
Name change?

### ISSUE THREAD

**Issue by aborsu** [Sagacify/komitet-gita-bezopasnosti#14]
Some people could find КGБ offensive.
This issue is here to propose alternative names.

**Comment by aborsu** [comment]
G.I.A.
Git Intelligence Agency

**Comment by aborsu** [comment]
Judge Git: cfr [Judge Dredd](https://en.wikipedia.org/wiki/Judge_Dredd#The_Judge_system)
linter, blamer and commenter

**Comment by aborsu** [comment]
GQC:
Git Quality Control

**Comment by aborsu** [comment]
Gitapo:
Git Approval Organization

**Comment by kfrancoi** [comment]
S.I.A
Sagacify Intelligence Agency
