### ISSUE TITLE
Better releases

### ISSUE THREAD

**Issue by kxepal** [Sagacify/komitet-gita-bezopasnosti#23]
Would be nice to see [there](https://github.com/Sagacify/komitet-gita-bezopasnosti/releases) some meaningful information about release version and changes. Probably do annotated tags or use GitHub releases?

**Comment by aborsu** [comment]
What do you have in mind?

I'm planning to add a changelog to the releases soon, but I haven't had time to get around it. Or did you mean something else?

**Comment by kxepal** [comment]
Well, something like [this](https://github.com/KeepSafe/aiohttp/releases) - headline as version and short annotation, body is about changelog. This is what subscribers get when you publish new release on GitHub and makes easy to notice it without confusing with a regular issue.

Just a wish anyway (:

**Comment by aborsu** [comment]
Is this better?
https://github.com/Sagacify/komitet-gita-bezopasnosti/releases/tag/v0.1.2

**Comment by kxepal** [comment]
@aborsu absolutely! :+1:
